### ISSUE TITLE
adicionar bloqueio de palavras reservadas do Delphi no nome da property

### ISSUE THREAD

**Issue by andreangelucci** [AndreAngelucci/gerador-classes-delphi#1]
https://www.portaleducacao.com.br/conteudo/artigos/informatica/palavras-reservadas-do-delphi-7/66210

**Comment by eduardovpessoa** [comment]
Alguma atualização sobre palavras reservadas? @AndreAngelucci 
Precisava muito dessa feature!

**Comment by andreangelucci** [comment]
@eduardovpessoa por enquanto ainda não.
